cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.ClienteList.as_view(), name="index"),
    path("crear/", views.ClienteCreate.as_view(), name="cliente_create"),
    path("detail/<int:pk>", views.ClienteDetail.as_view(), name="cliente_detail"),
    path("update/<int:pk>", views.ClienteUpdate.as_view(), name="cliente_update"),
    path("delete/<int:pk>", views.ClienteDelete.as_view(), name="cliente_delete"),
]

compras/urls.py
from django.urls import path

from . import views

app_name = "compras"

urlpatterns = [
    path("", views.index, name="index"),
    path("crear/", views.ComprasCreate.as_view(), name="crear"),
    path("buscar/", views.buscar, name="buscar"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include("home.urls")),
    path('cliente/', include("cliente.urls")),
    path('stock/', include("stock.urls")),
    path('compras/', include("compras.urls")), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

app_name = "home"

urlpatterns = [
    path("", TemplateView.as_view(template_name="home/index.html"), name="index"),
    path("login/", LoginView.as_view(template_name="home/login.html", next_page="home:index"), name="login"),
    path("logout/", LogoutView.as_view(template_name="home/logout.html"), name="logout"),
    path("about/", TemplateView.as_view(template_name="home/about.html"), name="about"),
]

urlpatterns += staticfiles_urlpatterns()

stock/urls.py
from django.urls import path

from . import views

app_name = "stock"

urlpatterns = [
    path("", views.index, name="index"),
    path("crear/", views.StockCreate.as_view(), name="crear"),
    path("buscar/", views.buscar, name="buscar"),
    path("delete/<int:pk>", views.StockDelete.as_view(), name="stock_delete"),
    path("update/<int:pk>", views.StockUpdate.as_view(), name="stock_update"),
    path("detail/<int:pk>", views.StockDetail.as_view(), name="stock_detail"),
    
]

home/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }

home/templates/home/about.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}
    <h2>Acerca de mi</h2>
{% endblock title %}
{% block content %}
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0"
             src=" {% static 'home/img/foto.jpeg' %}" />
    </div>
    <p>
        Site Reliability Engineer con más de quince años de experiencia en diferentes áreas de TI y Telecomunicaciones. Me desarrollé en diferentes áreas como Soporte de Aplicaciones, VOIP, Datos y actualmente en Operación Cloud. Siempre tuve la oportunidad de trabajar con la mayoría de los sectores involucrados en el ciclo de vida de las aplicaciones, lo que me permitió empatizar con cada uno de ellos y ayudarlos en sus problemas diarios.
        Me considero una persona amigable, inquieta y apasionada por la tecnología. Valoro las ganas de aprender en mis compañeros y siempre estoy dispuesto a ayudar y ser ayudado, ya que creo que cada día aprendo algo nuevo.
    </p>
    <p>
        <a href="https://www.linkedin.com/in/rodriguezemanuel/">
            <img src="{% static 'home/img/linkedin.png' %}" alt=" Linkedin">
        </a>
    </p>
    <p>
        <a class="btn btn-secondary justify-content-around"
           href="{% url 'home:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bienvenido a mi primera tienda ONLINE</title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href=" {% static 'home/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav>
            {% include "home/navbar.html" %}
        </nav>
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            {% block title %}
            {% endblock title %}
            {% block content %}
            {% endblock content %}
            <!-- Footer-->
            <footer class="py-5 bg-dark">
                <div class="container px-4 px-lg-5">
                    <p class="m-0 text-center text-white">Copyright &copy; Emanuel Rodriguez 2023</p>
                </div>
            </footer>
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src="/static/home/js/scripts.js"></script>
        </body>
    </html>

home/templates/home/index.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}
    <!--h2>Index Home</h2 -->
{% endblock title %}
{% block content %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
            <img class="img-fluid rounded mb-4 mb-lg-0 mt-5"
                 src=" {% static 'home/img/tienda.webp' %}" />
        </div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">Hola de nuevo... 👋</h1>
            <p>En esta tienda online podras gestionar tus clientes, consultar el stock disponible y registrar tus compras.</p>
        </div>
    </div>
{% endblock content %}

home/templates/home/login.html
{% extends 'home/base.html' %}
{% block content %}
    <div class="mt-4 mb-5">
        <form action="{% url 'home:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-grid gap-3">
                <button type="submit" class="btn btn-success">Iniciar sesión</button>
            </div>
        </form>
    </div>
{% endblock content %}

home/templates/home/logout.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
    <div class="mt-4 mb-5">
        <p class="fs-3 fst-italic ">Has cerrado sesión, esperamos verte pronto !!!</p>
        <br />
        <img class="img-fluid rounded mb-5 mb-lg-0 mt-5"
             src=" {% static 'home/img/forest.gif' %}" />
    </div>
{% endblock content %}

home/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Bienvenido <span class="text-primary">{{ user.username }}</span> a mi primera tienda ON-LINE</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active"
                           aria-current="page"
                           href="{% url "home:index" %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "cliente:index" %}">Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "compras:index" %}">Compras</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "stock:index" %}">Stock</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_staff %}
                            <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "home:about" %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "home:logout" %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active"
                           aria-current="page"
                           href="{% url "home:index" %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "home:about" %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "home:login" %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>