cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.ClienteList.as_view(), name="index"),
    path("crear/", views.ClienteCreate.as_view(), name="cliente_create"),
    path("detail/<int:pk>", views.ClienteDetail.as_view(), name="cliente_detail"),
    path("update/<int:pk>", views.ClienteUpdate.as_view(), name="cliente_update"),
    path("delete/<int:pk>", views.ClienteDelete.as_view(), name="cliente_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include("home.urls")),
    path('cliente/', include("cliente.urls")),
    path('stock/', include("stock.urls")),
    path('compras/', include("compras.urls")), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

app_name = "home"

urlpatterns = [
    path("", TemplateView.as_view(template_name="home/index.html"), name="index"),
    path("login/", LoginView.as_view(template_name="home/login.html", next_page="home:index"), name="login"),
    path("logout/", LogoutView.as_view(template_name="home/logout.html"), name="logout"),
    path("about/", TemplateView.as_view(template_name="home/about.html"), name="about"),
]

urlpatterns += staticfiles_urlpatterns()

cliente/models.py
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.nombre
    
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    nacimiento = models.DateField(null=True)
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True)
    imagen = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.nombre} {self.apellido}"
    

cliente/forms.py
from django import forms
from . import models

class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = "__all__"

        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "nacimiento": forms.DateInput(attrs={"class": "form-control"}),
            "pais_origen_id.name": forms.TextInput(attrs={"class": "form-control"}),
            "imagen": forms.ClearableFileInput(attrs={"class": "form-control-file"}),
        }

cliente/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from . import forms, models

class ClienteList(ListView):
    model = models.Cliente

    def get_queryset(self):
        if self.request.GET.get("buscar"):
            consulta = self.request.GET.get("buscar")
            object_list = models.Cliente.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Cliente.objects.all()
        return object_list


class ClienteCreate(CreateView):
    model = models.Cliente
    form_class = forms.ClienteForm
    success_url = reverse_lazy("cliente:index")


class ClienteDetail(DetailView):
    model = models.Cliente


class ClienteUpdate(UpdateView):
    model = models.Cliente
    form_class = forms.ClienteForm
    success_url = reverse_lazy("cliente:index")


class ClienteDelete(DeleteView):
    model = models.Cliente
    success_url = reverse_lazy("cliente:index")

cliente/templates/cliente/agregar_pais.html
{% extends "home/base.html" %}
{% block title %}
    <h2>Agregar pais</h2>
{% endblock title %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'cliente:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

cliente/templates/cliente/cliente_confirm_delete.html
{% extends 'home/base.html' %}
{% block title %}
    Eliminar Cliente
{% endblock title %}
{% block content %}
    <p class="fs-5 fst-italic">¿Está seguro de eliminar el cliente {{ object.nombre }} {{ object.apellido }}?</p>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row mt-4">
            <button type="submit" class="btn btn-danger">Confirmar</button>
        </div>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'cliente:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

cliente/templates/cliente/cliente_detail.html
{% extends 'home/base.html' %}
{% block title %}
    Vista en detalle
{% endblock title %}
{% block content %}
    <ul>
        <li>
            <strong>ID:</strong> {{ object.id }}
            <li>
                <strong>Nombre:</strong> {{ object.nombre }}
                <li>
                    <strong>Apellido:</strong> {{ object.apellido }}
                    <li>
                        <strong>Fecha de nacimiento:</strong> {{ object.nacimiento }}
                        <li>
                            <strong>Pais:</strong> {{ object.pais_origen_id }}
                            {% if object.imagen %}
                                <li>
                                    <strong>Imagen:</strong>
                                    <br>
                                    <img src="{{ object.imagen.url }}"
                                         alt="{{ object.nombre }}'s Imagen"
                                         style="max-width: 300px">
                                </li>
                            {% endif %}
                        </ul>
                        <p>
                            <a class="btn btn-secondary justify-content-around mt-4"
                               href="{% url 'cliente:index' %}">Ir al inicio</a>
                        </p>
                    {% endblock content %}

cliente/templates/cliente/cliente_form.html
{% extends 'home/base.html' %}
{% block title %}
    Cliente
{% endblock title %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row mt-4">
            <button type="submit" class="btn btn-success">Guardar</button>
        </div>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'cliente:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

cliente/templates/cliente/cliente_list.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}
    <h2>Clientes</h2>
{% endblock title %}
{% block content %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
            <img class="img-fluid rounded mb-4 mb-lg-0"
                 src=" {% static 'home/img/clientes.jpeg' %}" />
        </div>
        <table class="table table-hover table-responsive table-condensed" border="0">
            <thead>
                <tr class="d-flex">
                    <th class="col-1">Nombre</th>
                    <th class="col-3">Apellido</th>
                    <th class="col-5">País</th>
                    <th class="col-7">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in object_list %}
                    <tr class="d-flex">
                        <td class="col-1">
                            {{ cliente.nombre | capfirst }}
                            <td class="col-3">
                                {{ cliente.apellido | capfirst }}
                                <td class="col-5">
                                    {{ cliente.pais_origen_id.nombre| capfirst }}
                                    <td class="col-7">
                                        <div class="btn-group">
                                            <a href="{% url 'cliente:cliente_detail' cliente.id %}"
                                               class="btn btn-secondary btn-sm">Detalle</a>
                                            {% if user.is_staff %}
                                                <a href="{% url 'cliente:cliente_update' cliente.id %}"
                                                   class="btn btn-primary btn-sm">Actualizar</a>
                                                <a href="{% url 'cliente:cliente_delete' cliente.id %}"
                                                   class="btn btn-danger btn-sm">Eliminar</a>
                                            {% endif %}
                                        </div>
                                    </tr>
                                {% empty %}
                                    <tr class="d-flex">
                                        <td colspan="3">No se encontraron resultados.</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col-6">
                        <a href="{% url 'cliente:cliente_create' %}"
                           class="btn btn-success btn-lg mb-4 ">Crear Cliente</a>
                    </div>
                {% endblock content %}

cliente/templates/cliente/crear.html
{% extends "home/base.html" %}
{% block title %}
    <h2>Crear cliente</h2>
{% endblock title %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'cliente:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}