config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include("home.urls")),
    path('cliente/', include("cliente.urls")),
    path('stock/', include("stock.urls")),
    path('compras/', include("compras.urls")), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

app_name = "home"

urlpatterns = [
    path("", TemplateView.as_view(template_name="home/index.html"), name="index"),
    path("login/", LoginView.as_view(template_name="home/login.html", next_page="home:index"), name="login"),
    path("logout/", LogoutView.as_view(template_name="home/logout.html"), name="logout"),
    path("about/", TemplateView.as_view(template_name="home/about.html"), name="about"),
]

urlpatterns += staticfiles_urlpatterns()

stock/urls.py
from django.urls import path

from . import views

app_name = "stock"

urlpatterns = [
    path("", views.index, name="index"),
    path("crear/", views.StockCreate.as_view(), name="crear"),
    path("buscar/", views.buscar, name="buscar"),
    path("delete/<int:pk>", views.StockDelete.as_view(), name="stock_delete"),
    path("update/<int:pk>", views.StockUpdate.as_view(), name="stock_update"),
    path("detail/<int:pk>", views.StockDetail.as_view(), name="stock_detail"),
    
]

stock/models.py
from django.db import models

class Ubicacion(models.Model):
    ubicacion = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.ubicacion

class Stock(models.Model):
    articulo = models.CharField(max_length=100)
    precio = models.IntegerField()
    peso = models.IntegerField()
    cantidad = models.IntegerField()
    ubicacion_id = models.ForeignKey(Ubicacion, on_delete=models.SET_NULL, null=True, blank=True)
    imagen = models.ImageField(upload_to='images/', null=True, blank=True)
    descripcion = models.CharField(max_length=500, null=True, blank=True)
    def __str__(self):
        return self.articulo
    

stock/forms.py
from django import forms
from . import models

class StockForm(forms.ModelForm):
    class Meta:
        model = models.Stock
        fields = "__all__"

        widgets = {
            "articulo": forms.TextInput(attrs={"class": "form-control"}),
            "precio": forms.TextInput(attrs={"class": "form-control"}),
            "peso": forms.TextInput(attrs={"class": "form-control"}),
            "cantidad": forms.TextInput(attrs={"class": "form-control"}),
            "ubicacion_id.name": forms.TextInput(attrs={"class": "form-control"}),
            "imagen": forms.ClearableFileInput(attrs={"class": "form-control-file"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        }

class BuscarPorUbicacion(forms.Form):
    ubicacion = forms.ModelChoiceField(queryset=models.Ubicacion.objects.all(),label='Buscar por ubicacion', widget=forms.Select(attrs={'class': 'form'}))

stock/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic import DetailView, CreateView

from . import models, forms
from .models import Stock, Ubicacion
from .forms import *

# Create your views here.
def index(request):
    stock = Stock.objects.all()

    return render(request, "stock/index.html", {"stock": stock})


class StockCreate(CreateView):
    model = models.Stock
    form_class = StockForm
    success_url = reverse_lazy("stock:index")

def buscar(request):
    resultados = []

    if request.method == 'POST':
        form = BuscarPorUbicacion(request.POST)
        if form.is_valid():
            ubicacion = form.cleaned_data['ubicacion']
            try:
                ubicacion = Ubicacion.objects.get(ubicacion=ubicacion)
                resultados = Stock.objects.filter(ubicacion_id=ubicacion)
            except Stock.DoesNotExist:
                resultados = []
    
    else:
        form = BuscarPorUbicacion()

    return render(request, 'stock/buscar.html', {'form': form, 'resultados': resultados})

class StockUpdate(UpdateView):
    model = models.Stock
    form_class = StockForm
    success_url = reverse_lazy("stock:index")


class StockDelete(DeleteView):
    model = models.Stock
    success_url = reverse_lazy("stock:index")

class StockDetail(DetailView):
    model = models.Stock

stock/templates/stock/buscar.html
{% extends "home/base.html" %}
{% block title %}
    <title>Buscar Stock por ubicacion</title>
{% endblock title %}
{% block content %}
    <h1>Buscar Stock por ubicacion</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Buscar</button>
    </form>
    <h2>Resultados:</h2>
    <div class="col-lg-5">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Articulo</th>
                    <th>Cantidad</th>
                </tr>
            </thead>
            <tbody>
                {% for stock in resultados %}
                    <tr>
                        <td>{{ stock.articulo }}</td>
                        <td>{{ stock.cantidad }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>No se encontraron resultados.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'stock:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

stock/templates/stock/crear.html
{% extends "home/base.html" %}
{% block title %}
    <h2>Agregar articulo</h2>
{% endblock title %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row mt-4">
            <button type="submit" class="btn btn-success">Guardar</button>
        </div>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'stock:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

stock/templates/stock/index.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}
    <h2>Stock</h2>
{% endblock title %}
{% block content %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-md-6">
            <img class="img-fluid float-right"
                 src=" {% static 'home/img/stock.jpeg' %}"
                 style="max-width: 600px" />
        </div>
        <div class="col-md-6">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Articulo</th>
                        <th>Precio</th>
                        <th>Peso</th>
                        <th>Cantidad</th>
                        <th>Ubicacion</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stock in stock %}
                        <tr>
                            <td>{{ stock.articulo }}</td>
                            <td>{{ stock.precio }}</td>
                            <td>{{ stock.peso }}</td>
                            <td>{{ stock.cantidad }}</td>
                            <td>{{ stock.ubicacion_id }}</td>
                            <td>
                                <div class="btn-group">
                                    <a href="{% url 'stock:stock_detail' stock.id %}"
                                       class="btn btn-secondary btn-sm">Detalle</a>
                                    {% if user.is_staff %}
                                        <a href="{% url 'stock:stock_update' stock.id %}"
                                           class="btn btn-primary btn-sm">Actualizar</a>
                                        <a href="{% url 'stock:stock_delete' stock.id %}"
                                           class="btn btn-danger btn-sm">Eliminar</a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3">No se encontraron resultados.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="btn-group d-flex justify-content-between mt-5">
            <p>
                <a class="btn btn-primary" href="{% url 'stock:crear' %}">Agregar articulo</a>
            </p>
            <p>
                <a class="btn btn-primary" href="{% url 'stock:buscar' %}">Buscar por ubicacion</a>
            </p>
            <p>
                <a class="btn btn-secondary" href="{% url 'home:index' %}">Ir al inicio</a>
            </p>
        </div>
    </div>
{% endblock content %}

stock/templates/stock/stock_confirm_delete.html
{% extends 'home/base.html' %}
{% block title %}
    <h2>Eliminar Articulo</h2>
{% endblock title %}
{% block content %}
    <p class="fs-5 fst-italic">¿Está seguro de eliminar el articulo {{ object.articulo }} ?</p>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row mt-4">
            <button type="submit" class="btn btn-danger">Confirmar</button>
        </div>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'stock:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

stock/templates/stock/stock_detail.html
{% extends 'home/base.html' %}
{% block title %}
    Vista en detalle
{% endblock title %}
{% block content %}
    <ul>
        <li>
            <strong>ID:</strong> {{ object.id }}
            <li>
                <strong>Articulo:</strong> {{ object.articulo }}
                <li>
                    <strong>Precio:</strong> {{ object.precio }}
                    <li>
                        <strong>Peso:</strong> {{ object.peso }}
                        <li>
                            <strong>Ubicacion:</strong> {{ object.ubicacion_id }}
                            <li>
                                <strong>Canrtidad:</strong> {{ object.cantidad }}
                                {% if object.imagen %}
                                    <li>
                                        <strong>Imagen:</strong>
                                        <br>
                                        <img src="{{ object.imagen.url }}"
                                             alt="{{ object.articulo }}'s Imagen"
                                             style="max-width: 300px">
                                    </li>
                                {% endif %}
                                <li>
                                    <strong>Descripcion:</strong> {{ object.descripcion }}
                                </ul>
                                <p>
                                    <a class="btn btn-secondary justify-content-around mt-4"
                                       href="{% url 'stock:index' %}">Ir al inicio</a>
                                </p>
                            {% endblock content %}

stock/templates/stock/stock_form.html
{% extends 'home/base.html' %}
{% block title %}
    <h2>Editar Articulo {{ object.articulo }}</h2>
{% endblock title %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row mt-4">
            <button type="submit" class="btn btn-success ">Guardar</button>
        </div>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'stock:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}