compras/urls.py
from django.urls import path

from . import views

app_name = "compras"

urlpatterns = [
    path("", views.index, name="index"),
    path("crear/", views.ComprasCreate.as_view(), name="crear"),
    path("buscar/", views.buscar, name="buscar"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include("home.urls")),
    path('cliente/', include("cliente.urls")),
    path('stock/', include("stock.urls")),
    path('compras/', include("compras.urls")), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

app_name = "home"

urlpatterns = [
    path("", TemplateView.as_view(template_name="home/index.html"), name="index"),
    path("login/", LoginView.as_view(template_name="home/login.html", next_page="home:index"), name="login"),
    path("logout/", LogoutView.as_view(template_name="home/logout.html"), name="logout"),
    path("about/", TemplateView.as_view(template_name="home/about.html"), name="about"),
]

urlpatterns += staticfiles_urlpatterns()

stock/urls.py
from django.urls import path

from . import views

app_name = "stock"

urlpatterns = [
    path("", views.index, name="index"),
    path("crear/", views.StockCreate.as_view(), name="crear"),
    path("buscar/", views.buscar, name="buscar"),
    path("delete/<int:pk>", views.StockDelete.as_view(), name="stock_delete"),
    path("update/<int:pk>", views.StockUpdate.as_view(), name="stock_update"),
    path("detail/<int:pk>", views.StockDetail.as_view(), name="stock_detail"),
    
]

compras/models.py
from django.db import models
from stock import models as stock_models

class Categoria(models.Model):
    categoria = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.categoria


class Compras(models.Model):
    articulo = models.CharField(max_length=100)
    #articulo = models.ForeignKey(stock_models.Stock, on_delete=models.SET_NULL, null=True, blank=True)
    precio = models.IntegerField()
    cantidad = models.IntegerField()
    categoria_id = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.articulo} {self.precio} {self.cantidad} {self.categoria_id}"

compras/forms.py
from django import forms
from stock.models import Stock
from . import models

class ComprasForm(forms.ModelForm):
    
    articulo = forms.ModelChoiceField(queryset=Stock.objects.all(), label="Articulo",  widget=forms.Select(attrs={'class': 'form'}))

    widgets = {
        "articulo": forms.Select(attrs={'class': 'form-control'}),
        "precio": forms.NumberInput(attrs={'class': 'form-control'}),
        "cantidad": forms.NumberInput(attrs={'class': 'form-control'}),
        "categoria_id": forms.Select(attrs={'class': 'form-control'}),
    }

    class Meta:
        model = models.Compras
        fields = "__all__"


class BuscarPorCategoria(forms.Form):
    categoria = forms.ModelChoiceField(queryset=models.Categoria.objects.all(),label='Buscar por categoria', widget=forms.Select(attrs={'class': 'form'}))

compras/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Categoria, Compras
from django.views.generic import CreateView
from .forms import *
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your views here.
def index(request):
    compras = Compras.objects.all()

    return render(request, "compras/index.html", {"compras": compras})

class ComprasCreate(CreateView):
    model = models.Compras
    form_class = ComprasForm
    success_url = reverse_lazy("compras:index")

def buscar(request):
    resultados = []

    if request.method == 'POST':
        form = BuscarPorCategoria(request.POST)
        if form.is_valid():
            categoria = form.cleaned_data['categoria']
            try:
                categoria = Categoria.objects.get(categoria=categoria)
                resultados = Compras.objects.filter(categoria_id=categoria)
            except Compras.DoesNotExist:
                resultados = []
    
    else:
        form = BuscarPorCategoria()

    return render(request, 'compras/buscar.html', {'form': form, 'resultados': resultados})

compras/templates/compras/buscar.html
{% extends "home/base.html" %}
{% block title %}
    <title>Buscar Compras por categoria</title>
{% endblock title %}
{% block content %}
    <h1>Buscar Compras por categoria</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Buscar</button>
    </form>
    <h2>Resultados:</h2>
    <div class="col-lg-5">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Articulo</th>
                    <th>Cantidad</th>
                </tr>
            </thead>
            <tbody>
                {% for stock in resultados %}
                    <tr>
                        <td>{{ stock.articulo }}</td>
                        <td>{{ stock.cantidad }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>No se encontraron resultados.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'compras:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

compras/templates/compras/compras_form.html
{% extends 'home/base.html' %}
{% block title %}
    <h2>Agregar nueva compra {{ object.articulo }}</h2>
{% endblock title %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row mt-4">
            <button type="submit" class="btn btn-success ">Guardar</button>
        </div>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'stock:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

compras/templates/compras/crear.html
{% extends "home/base.html" %}
{% block title %}
    <h2>Cargar compra</h2>
{% endblock title %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    <p>
        <a class="btn btn-secondary justify-content-around mt-4"
           href="{% url 'compras:index' %}">Ir al inicio</a>
    </p>
{% endblock content %}

compras/templates/compras/index.html
{% extends "home/base.html" %}
{% load static %}
{% block title %}
    <h2>Compras</h2>
{% endblock title %}
{% block content %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
            <img class="img-fluid rounded mb-4 mb-lg-0"
                 src=" {% static 'home/img/compras.jpeg' %}" />
        </div>
        <div class="col-lg-5">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Articulo</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                        <th>Categoria</th>
                        <th>Fecha de Compra</th>
                    </tr>
                </thead>
                <tbody>
                    {% for compras in compras %}
                        <tr>
                            <td>{{ compras.articulo }}</td>
                            <td>{{ compras.precio }}</td>
                            <td>{{ compras.cantidad }}</td>
                            <td>{{ compras.categoria_id }}</td>
                            <td>{{ compras.timestamp|date:"Y-m-d" }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3">No se encontraron resultados.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="btn-group d-flex justify-content-around mt-5">
            <p>
                <a class="btn btn-primary" href="{% url 'compras:crear' %}">Agregar compra</a>
            </p>
            <p>
                <a class="btn btn-primary" href="{% url 'compras:buscar' %}">Buscar por categoria</a>
            </p>
            <p>
                <a class="btn btn-secondary" href="{% url 'home:index' %}">Ir al inicio</a>
            </p>
        </div>
    </div>
{% endblock content %}